### ISSUE TITLE
Array reducer creates multiple documents. 

### ISSUE THREAD

**Issue by alexmills** [medihack/redux-pouchdb-plus#1]
Hey mate, I'm still wrapping my head around redux and your plugin but I was wondering how hard do you reckon it would be to modify it so that for reducers that return arrays, each item gets its own document?

**Comment by medihack** [comment]
Hi Alex. Sorry for the late reply. This would be quite hard and better be implemented from scratch. I saw some library that does it that way (don't remember the name), but it was far from complete.
