### ISSUE TITLE
How to rehydrate when offline?

### ISSUE THREAD

**Issue by devinle** [medihack/redux-pouchdb-plus#17]
Hello,

First off, great job! I'm just hoping for a quick confirmation on something if you have a few minutes.

My assumption is that redux-pouchdb-plus automatically hydrates the state of a react native application when offline. Is this not correct? I understand that the core functionality is saving/syncing redux state to pouchdb.  I'm not using couchdb in my application. My need is to hydrate my app with state from pouchdb if a user is offline.

Thanks for your time.
Devin

**Comment by devinle** [comment]
Further to this, I am seeing in the source code a function called **setReducer**

It appears as though it should be hydrating state from pouchdb. I must be missing something.

For clarity, the persistence is working and I can see my reducer docs just fine. It's just the hydration that doesn't seem to be functioning.

Thanks again.
Devin

**Comment by medihack** [comment]
Hy Devin. All what redux-pouchdb-plus does is sync the redux state (or a part of it) with Pouchdb. In a web app when you go offline Pouchdb is still available as it runs locally in the browser. Pouchdb just may loose its connection to a non local Couchdb. When going online again Couchdb may update Pouchdb and then Pouchdb updates the Redux state (by using the set Reducer function, https://github.com/medihack/redux-pouchdb-plus/blob/master/src/index.js#L143.
I would have assumed that it works the same way with react native. Isn't pouchdb there locally installed, too?

**Comment by devinle** [comment]
Thanks for your reply @medihack 

I have pouchdb-react-native and redux-pouchdb-plus both running locally on the device. I'm not using CouchDB for this project, but in the future, I might add it.

Basically, I'm hoping for the app to boot up and hydrate the Redux state from redux-pouchdb-plus automatically if the user is offline. So any persistent data the user has would auto populate the application. Is that how setReducer works? It will automatically fire and apply the persistent data to Redux?

Also, I'm currently building the app using create-react-native-app. What I'm wondering is, if I'm continuously developing, and the bundle is continuously rebuilding, I assume the persistent storage would be destroyed? Will this only work when the app is fully built and running? Currently, I can't seem to get the state persisting in development mode.

Thanks for your patience!
And your help!
Devin

**Comment by devinle** [comment]
Hi @medihack,

Apologies for the multiple messages. It may have been a reference key error on my part, but it seems to be working now whenever I rebundle the application. I'll let you know if anything more comes up, but it appears as though the setReducer is auto running.

Thanks again!
Devin
