### ISSUE TITLE
How to initialize the preloadedState for createStore() by using the data stored in pouchDB?

### ISSUE THREAD

**Issue by NevenLeung** [medihack/redux-pouchdb-plus#20]
What is the right way to make this task done?

I have tried some approaches to make it.

---

1. Just use the pouchDB api [b.allDocs()](https://pouchdb.com/api.html#batch_fetch) to fetch all the data, and make it as the preloadedState, pass it to `createStore()`

```js
async function getAllDataFromDB(db) {
  try {
    return db.allDocs();
  } catch (e) {
    console.log(e);
    return undefined;
  }
}
```
Because there is no option object in `db.allDocs()`, the result only contains the `id`, `key` and `value` fileds, no the data filed. The result got from pouchDB is like this. 
```json
{
  "offset": 0,
  "total_rows": 1,
  "rows": [{
    "id": "counter",
    "key": "counter",
    "value": {
      "rev": "1-5782E71F1E4BF698FA3793D9D5A96393"
    }
  }]
}
```

However, it could be correctly set the store correctly.

---

2. Set the option object to `{include_docs: true}`. It could bring the data back.

```js
async function getAllDataFromDB(db) {
  try {
    return db.allDocs({include_docs: true});
  } catch (e) {
    console.log(e);
    return undefined;
  }
}
```

The result got from pouchDB is like this. This approach does also work.

```json
{
  "offset": 0,
  "total_rows": 1,
  "rows": [{
    "doc": {
      "_id": "counter",
      "_rev": "1-5782E71F1E4BF698FA3793D9D5A96393",
      "state": "2",
    },
    "id": "counter",
    "key": "counter",
    "value": {
      "rev": "1-5782E71F1E4BF698FA3793D9D5A96393"
    }
  }]
}
```

---

3. Extract the data from the result, make the state object on my own. Because the data structrue of result got from pouchdb is very different from the state in redux. 

So, I think there is some magics in redux-pouchdb-plus.

```js
async function getAllDataFromDatabase(db) {
  try {
    let result = {};

    const data = await db.allDocs({include_docs: true}); 
    data.rows.map((item) => result[item.id] = item.doc.state);

    return result;
  } catch (e) {
    console.log(e);

    return undefined;
  }
}
```

This approach does also work. It is the recommended way in my opinion. Do I need to do this on my own? Or just do it in approach No.1 or No.2? 

----

In addition, if I do this in approach No.1 or No.2, when I use [redux-async-initial-state](https://github.com/KELiON/redux-async-initial-state), redux-async-initial-state enhancer will throw an error massage 

```
Unexpected keys "total_rows", "offset", "rows" found in previous state received by the reducer. 
Expected to find one of the known reducer keys instead: "counter". Unexpected keys will be ignored.
```

It will make the state of counter to be reset to 0, as the default value in counter reducer.

--- 

Another similar question: What is the right way to use the data stored in pouchdb as `preloadedState` to `createStore()` in redux?

Any advice is appreciated.

**Comment by alexiri** [comment]
I'm new to this, and I also have this question. @NevenLeung, what's the best approach in the end?
