### ISSUE TITLE
Add 'isEqual', 'toPouch', and 'fromPouch' to 'reducerOptions'.

### ISSUE THREAD

**Issue by wtgtybhertgeghgtwtg** [medihack/redux-pouchdb-plus#3]
This would allow `immutable` support without having it as a dependency.  To use `immutable`, the user would have to do something like

```
import { fromJS, is, toJS } from 'immutable';
const finalReducer = persistentReducer(counter, { isEqual: is, toPouch: toJS, fromPouch: fromJS });
```

It's a little more work for them, but shaves off three dependencies from the package and allows users that do not use `immutable` to avoid bundling things they don't need.

**Comment by marsch** [comment]
+1

**Comment by medihack** [comment]
Better late than never ;-)
