### ISSUE TITLE
How to install latest version?

### ISSUE THREAD

**Issue by riddla** [medihack/redux-pouchdb-plus#9]
(First and foremost: thank you for a great library 👍)

I think the version published latest on https://www.npmjs.com/package/redux-pouchdb-plus/ respectively `0.8.1` does not include the `custom name for PouchDB document` mentioned in the Readme. Can you release it or give me instructions to include/build it myself?

The feature is very interesting for my current project ...

**Comment by MaxSvargal** [comment]
+1, why no updates in npm?

**Comment by MaxSvargal** [comment]
@riddla i'll make a fork with updated dependencies `npm i redux-pouchdb-rethink`

**Comment by medihack** [comment]
Sorry for the late reply. I just updated the NPM package.
